name: '[Manual] Test Testnet'
on: workflow_dispatch

jobs:
  tests:
    name: Run test on ${{ matrix.name }}
    strategy:
      max-parallel: 1 # needed until we get a seperate account for the rpc provider, until then running them in parallel would result in a nonce issue
      matrix:
        name: [sequencer-goerli, rpc-goerli]
        include:
          - name: sequencer-goerli
          - name: rpc-goerli

    uses: ./.github/workflows/_test.yml
    secrets:
      TEST_PROVIDER_BASE_URL: ${{ secrets.TEST_PROVIDER_BASE_URL }}
      TEST_RPC_URL: ${{ secrets.TEST_RPC_URL }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
