name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run docs
      - name: Do git actions
        run: |
          git config user.email "janek@argent.xyz"
          git config user.name "Docs Bot"
          git add --force -- docs/README.md
          git commit -m "docs: add generated docs"
      - name: Push to git branch for PR
        if: ${{ github.head_ref != '' }}
        run: git push origin HEAD:${{ github.head_ref }}
      - name: Push to git branch for branch
        if: ${{ github.head_ref == '' }}
        run: git push
