name: PR check
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  tests:
    strategy:
      max-parallel: 1 # needed until we get a seperate account for the rpc provider, until then running them in parallel would result in a nonce issue
      matrix:
        name: [sequencer-devnet, rpc-devnet]
        include:
          - name: sequencer-devnet
            TEST_PROVIDER_BASE_URL: http://127.0.0.1:5050/
          - name: rpc-devnet
            TEST_RPC_URL: http://127.0.0.1:5050/rpc
            
    name: Run test
    runs-on: ubuntu-latest
    needs: [build]

    services:
      devnet:
        image: shardlabs/starknet-devnet:0.4.0-seed0
        ports:
          - 5050:5050
    env:
      TEST_PROVIDER_BASE_URL: http://127.0.0.1:5050/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm test
